apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: default
spec:
  encryptedData:
    config.ini: AgB+KUXwa/WVmwCoUV7mCxWWAoGmf5B4+Mx6/j5CbV6WMBDgwrGQv74aPjvnMjOoP8a99Y0DE5gBQK18XsU0A8+vJDAFU7Zi/ssGoleR5T9G4BsT5CL5z4nsvNE/m8L9wKvYHETXuwMf9AjWr/AmJKPcURc8Oc2DBs/gawDO0oteWYzXRcnmghzzkyCVMQCDTGcuHsKTbLkXw5UKSnC+5N//HEm/iYJZqnPJQmce6grA+rqs2okuTOS9QB7HyLHJW49IwHtYn3+nsPEKE/hAEplxgUvNe23+LZlYoBYWIcvmYcIClvp9Oql9K0ALF3FHLNh9Kh0YPXgaGyFaRPZjzOscplQ5MWAL4ONm8AeujzTWB1iJD7GHiFu4lPJ+3vBQHEK4P4n7cQTz7TzjFz9D26Z3gyL31mCFslW/FtbycQK8OVNxAlhPFlF23W9NVOzhZr3jZKtoVpoXwTKGE5WsTFCS5RYh1xn2n+mfOYoe1GakeXI1bcSRO1wgucywXxnx227pVp0FocUw0/ZiMGD5m1b0B0fYOd83YTtuDbE1T6/olxkDYW3xvEqL1L1oeuqCb0wP70fhIM8SXegQrK9FJJLDpECJl2DtvlSuL4V6UirodTJ9wAV6s40ErHH/Bi8dMNGiNPsghbX7D7MvU0RHoYrLqWVGqaj5UHXl+gdhmcYbhk3E7nNlgO3JRcKjJGtTjUi4BMP49lSz1mwW0H8l4f5Le73zpteon8LhTUD0nc0uvyUAxBFMXi3sl5AW2F1+qesWeWch7dWSjkRlPPiwZMv9ZoHYlV5B/VuzdK4l0B+MnkL33SZJJcpM9FvIj1o/rE6eX0V9RVTPqPYF7LGTQIOD8DHR7AU/kJzoJD2E/FkxiwumM1ZgyxwtuZ0wFsudxUsPi0+OlEWqVDGkxAyGz3tHLCvXuLuSHBhZEW3iHSXLYbjhNdfMdLXCMe5NM8zjurWrxfFxhXksKsRWcPEZBtQRTABh8kgMQQ==
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: default

