apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    MARIADB_ROOT_PASSWORD: AgCMMbwn7Cn/VMKhYPUsgtCtBoODAKeOKT9PpzDY4fIs+w8F3zqQAZ8BgVKidH8ZWxoES/YZS6zM8zBOi2FyyHTd/rx4pGPOVZ7Roujid0Hdeiz25Qfzlh4QrhRoy18xxLuG0E2Yrj5jZ5YevVMwMyiWOYRJjIvibctFiXy0Msp6A+wBkGn8qlEwHk+IQoSA2nucek/StfLALGLrugyEyfmnexcJeAiIA8YVxfSFEnmGOTknaGvH0fln6/3A/mCgTlMCbV7VecJfu373yxB2UHDJ4X8fElXqzgflggEHpLelCbuZvOjr2JRVgp/zbfZlDjEPW7TbnZiHfK4VG1MWWAqCXA/vHkmL6q7j49LBUgHHnK2TAcXz/rs9TeHX/aWRdX+z2sLQOz06pD3NUeGYA5XBvK1+6IiNb6w12WFr8YL+GM5sxl/A1jxB7VR/oqIACbw0cLpt1En6Gu9hADNVYMvi8Js2iJtQBYNMvec1aK4rsw2hT8IvfiEEI96jqKQq4w2GDe37KDs3RHAOMCAn+tHkiLH9Stq//yt8/Ts2Qyzyip5W++AtiVnFuH7xCp3ScJ+CVDaBFHcKIerO6/dR9/lOt790HWUvkiTYAW5/kA9wEmC4MeFvhUL1RKKrPlT7bzZSZGgyoomXIskh7qnn7w02YB06Mypof5uHgkC34m+QUkuVKb6rKzdKVJdGF4O8i8s51Cr9GQAXnsd1F1oHKERl063MPw==
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default

