apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
spec:
  encryptedData:
    MARIADB_ROOT_PASSWORD: AgAxOj0dn/XT7+ZEB87HpuB0vLZMqms0ctacsHF/GCW4LhRcjGuvNJ+lwXdhEqS6L1pwF5maYfd9zt2doisB9QtffRlCWDVlLAB9FL1YDo2ttBp9D07E7GUl7OZvkTL+d/Y8ibeRyFt8ZB9j9bP7bgtJGnCwW30LCqhsBCZ7bmBXdrWbBxs81iPIVCVaX0lNAcPtC2XKik7utXqD+082CoGn2XQ0QhhD4DuMdolSdTqWpuxJGUmXkbcgIX3oCybwNf829q+55CcnKaIfOEQJoAYZYYlmgl20gBeAooaWmJ2xTs85ufTMju0sAal7bk8MfWTHKJCvTScTwq9Fp9MB26Sdujnn2iQebQJxcrhwLrAVfHFK7lhA/zAj9zPKGvPIYIQOL+az+9DLK+DV+IBd34hSTVeQA9CJS8q+RFlvuUc5sZVjMg37QkS9QidK9/AA0qMqt35FfhgTpxBlg22rQ4yELCECWaqmLIJCgEKLfIu+cxKZ3uQnBRweZi7jaV9VjgsPToxTSmrJ2wFJkAnG4/h1iX+EicapGrWED47pzDd7+WrQ50xBWAsafnEJyTOago0eE5Z81XNqU4sm5Ik64innUmBsg5pEIP8FIcuObIlu7uR9RTM2+IC0LgBUx6oG4wP13pTLHKgF0ZI+hUPll3gD77PlQv9y7ykWT34dizIP889pvEu6tTMk74H+v1SjiwWjtBadXcNiFPpvD6NiZr00uu3MOQ==
  template:
    metadata:
      creationTimestamp: null
      name: db-secret

