kind: ConfigMap
apiVersion: v1
metadata:
  name: env
data:
  OVERRIDE_HOSTNAME: mail.lapi.tokyo
  ENABLE_FETCHMAIL: "0"
  FETCHMAIL_POLL: "120"
  ENABLE_SPAMASSASSIN: "0"
  ENABLE_CLAMAV: "0"
  ENABLE_FAIL2BAN: "0"
  ENABLE_POSTGREY: "0"
  ONE_DIR: "1"
  DMS_DEBUG: "0"
  SSL_TYPE: "manual"
  SSL_CERT_PATH: "/etc/ssl/mailserver/tls.crt"
  SSL_KEY_PATH: "/etc/ssl/mailserver/tls.key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mailserver
  labels:
    app: docker-mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-mailserver
  template:
    metadata:
      labels:
        app: docker-mailserver
    spec:
      containers:
        - name: docker-mailserver
          image: mailserver/docker-mailserver:8.0
          ports:
          - name: smtp
            containerPort: 25
            protocol: TCP
          - name: smtp-secure
            containerPort: 465
            protocol: TCP
          - name: smtp-auth
            containerPort: 587
          - name: imap
            containerPort: 143
            protocol: TCP
          - name: imap-secure
            containerPort: 993
            protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /tmp/docker-mailserver/
              readOnly: true
            - name: opendkim
              mountPath: /tmp/docker-mailserver/opendkim/
              readOnly: true
            - name: opendkim-keys-lapi-gq
              mountPath: /tmp/docker-mailserver/opendkim/keys/lapi.tokyo
              readOnly: true
            - name: docker-mailserver-tls
              mountPath: /etc/ssl/mailserver
              readOnly: true
            - name: data
              mountPath: /var/mail
              subPath: data
            - name: data
              mountPath: /var/mail-state
              subPath: state
            - name: data
              mountPath: /var/log/mail
              subPath: log
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_PTRACE
          envFrom:
          - configMapRef:
              name: env
          - secretRef:
              name: relay-secret
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: config
              - secret:
                  name: postfix-accounts
        - name: opendkim
          configMap:
            name: opendkim
        - name: opendkim-keys-lapi-gq
          secret:
            secretName: opendkim-keys-lapi-gq
        - name: docker-mailserver-tls
          secret:
            secretName: docker-mailserver-tls
        - name: data
          persistentVolumeClaim:
            claimName: docker-mailserver
---
apiVersion: v1
kind: Service
metadata:
  name: docker-mailserver
spec:
  selector:
    app: docker-mailserver
  ports:
    - name: smtp
      port: 25
    - name: smtp-secure
      port: 465
    - name: smtp-auth
      port: 587
    - name: imap
      port: 143
    - name: imap-secure
      port: 993
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-mailserver
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
