apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mailserver
  labels:
    app: docker-mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-mailserver
  template:
    metadata:
      labels:
        app: docker-mailserver
    spec:
      containers:
        - name: docker-mailserver
          image: mailserver/docker-mailserver:latest
          ports:
            - containerPort: 25
            - containerPort: 143
            - containerPort: 587
            - containerPort: 993
          volumeMounts:
            - name: config
              mountPath: /tmp/docker-mailserver/
            - name: opendkim
              mountPath: /tmp/docker-mailserver/opendkim/
            - name: opendkim-keys-lapi-gq
              mountPath: /tmp/docker-mailserver/opendkim/keys/lapi.gq
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_PTRACE
          env:
            - name: HOSTNAME
              value: mail
            - name: DOMAINNAME
              value: lapi.gq
      volumes:
        - name: config
          configMap:
            name: config
        - name: opendkim
          configMap:
            name: opendkim
        - name: opendkim-keys-lapi-gq
          configMap:
            name: opendkim-keys-lapi-gq
---
apiVersion: v1
kind: Service
metadata:
  name: docker-mailserver
spec:
  selector:
    app: docker-mailserver
  ports:
    - name: smtp
      port: 25
    - name: esmtp
      port: 143
    - name: pop3
      port: 587
    - name: imap4
      port: 993
  type: LoadBalancer
