kind: ConfigMap
apiVersion: v1
metadata:
  name: env
data:
  OVERRIDE_HOSTNAME: lapi.gq
  ENABLE_FETCHMAIL: "0"
  FETCHMAIL_POLL: "120"
  ENABLE_SPAMASSASSIN: "0"
  ENABLE_CLAMAV: "0"
  ENABLE_FAIL2BAN: "0"
  ENABLE_POSTGREY: "0"
  ONE_DIR: "1"
  DMS_DEBUG: "0"
  SSL_TYPE: "manual"
  SSL_CERT_PATH: "/etc/ssl/mailserver/tls.crt"
  SSL_KEY_PATH: "/etc/ssl/mailserver/tls.key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mailserver
  labels:
    app: docker-mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-mailserver
  template:
    metadata:
      labels:
        app: docker-mailserver
    spec:
      containers:
        - name: docker-mailserver
          image: mailserver/docker-mailserver:latest
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
            - name: smtp-secure
              containerPort: 465
              protocol: TCP
            - name: smtp-auth
              containerPort: 587
            - name: imap
              containerPort: 143
              protocol: TCP
            - name: imap-secure
              containerPort: 993
              protocol: TCP
          volumeMounts:
            - name: config
              subPath: postfix-accounts.cf
              mountPath: /tmp/docker-mailserver/postfix-accounts.cf
              readOnly: true
            - name: config
              subPath: postfix-virtual.cf
              mountPath: /tmp/docker-mailserver/postfix-virtual.cf
              readOnly: true
            - name: config
              subPath: SigningTable
              mountPath: /tmp/docker-mailserver/opendkim/SigningTable
              readOnly: true
            - name: config
              subPath: KeyTable
              mountPath: /tmp/docker-mailserver/opendkim/KeyTable
              readOnly: true
            - name: config
              subPath: TrustedHosts
              mountPath: /tmp/docker-mailserver/opendkim/TrustedHosts
              readOnly: true
            - name: opendkim-keys
              mountPath: /tmp/docker-mailserver/opendkim/keys
              readOnly: true
            - name: docker-mailserver-tls
              mountPath: /etc/ssl/mailserver
              readOnly: true
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_PTRACE
          envFrom:
            - configMapRef:
                name: env
      volumes:
        - name: config
          configMap:
            name: config
        - name: opendkim-keys
          configMap:
            name: opendkim-keys
        - name: docker-mailserver-tls
          secret:
            secretName: docker-mailserver-tls
---
apiVersion: v1
kind: Service
metadata:
  name: docker-mailserver
spec:
  selector:
    app: docker-mailserver
  ports:
    - name: smtp
      port: 25
    - name: esmtp
      port: 143
    - name: pop3
      port: 587
    - name: imap4
      port: 993
  type: LoadBalancer
