apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-mailserver
  labels:
    manifest: helm
spec:
  project: default
  source:
    repoURL: "https://geek-cookbook.github.io/charts/"
    chart: docker-mailserver
    targetRevision: 0.3.0
    helm:
      values: |
        pod:
          dockermailserver:
            override_hostname: mail.lapi.gq
        service:
          type: LoadBalancer
        rainloop:
          ingress:
            hosts: rainloop.lapi.gq
        demoMode:
          enabled: true
        domains:
          - mail.lapi.gq
        ssl:
          issuer:
            name: letsencrypt-prod
          kind: ClusterIssuer
          dnsname: lapi.gq
          dns01provider: cloudflare
  destination:
    server: "https://kubernetes.default.svc"
    namespace: docker-mailserver
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
