apiVersion: apps/v1
kind: Deployment
metadata:
  name: lapi-website-gatsby-deployment
  labels:
    app: lapi-website-gatsby
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lapi-website-gatsby
  template:
    metadata:
      labels:
        app: lapi-website-gatsby
    spec:
      containers:
        - name: lapi-website-gatsby
          image: dragoneena12/lapi-website-gatsby:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lapi-website-gatsby-service
spec:
  selector:
    app: lapi-website-gatsby
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
