apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
- db-secret.yaml
- app-secret.yaml
- pvc.yaml
namespace: cdg-staging
configMapGenerator:
- name: next-env
  literals:
  - NEXT_PUBLIC_ORIGIN=https://cdg-stg.lapi.tokyo
  - NEXT_PUBLIC_API_URL=https://api.cdg-stg.lapi.tokyo/graphql
  - NEXT_PUBLIC_ASSETS_URL=https://api.cdg-stg.lapi.tokyo/static/
  - NEXT_PUBLIC_AUTH_CLIENT_ID=F6GbKXfELGjVePRisKIisyEFgDB0dVVi
  - NEXT_PUBLIC_AUTH0_DOMAIN=cdg-stg.jp.auth0.com
