apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdg-db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  selector:
    matchLabels:
      name: cdg-db-stg
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdg-static
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  selector:
    matchLabels:
      name: cdg-static-stg
