apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  labels:
    manifest: directory
spec:
  project: default
  source:
    repoURL: "https://github.com/dragoneena12/k8s-server-settings.git"
    path: argocd-apps
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
