apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  labels:
    manifest: helm
spec:
  project: default
  source:
    repoURL: "https://charts.jetstack.io"
    chart: cert-manager
    targetRevision: v1.1.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
