apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-configuration
  labels:
    manifest: helm
spec:
  project: default
  source:
    repoURL: "https://github.com/dragoneena12/k8s-server-settings.git"
    path: cert-manager-configuration
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
