apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ddns
  labels:
    manifest: directory
spec:
  project: default
  source:
    repoURL: "https://github.com/dragoneena12/k8s-server-settings.git"
    path: cloudflare-ddns
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudflare-ddns
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
