apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: grafana
      port: 3000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  serviceName: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:7.3.5
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-pvc
              mountPath: /var/lib/grafana
  volumeClaimTemplates:
    - metadata:
        name: grafana-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
