apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: lapi-hotel-system
spec:
  encryptedData:
    config.ini: AgANiH4QR0npBxqOjN2ez7B8SQcaE4zKpAtydhQ6Mcp6ZpEYGCmtbvsmgbjlVYNYtUiVjLPWRBaOqB9x0KYIaptRLf4fkYJElIlrP9f4EdGTJVb7tELHaZIJ+rTKC9/pBCBGCwUfxyr2tkQgoRtynvkccu4zmQj5LM+PyG+BhZxgsKdhr0/IyRxeoivBpY/XkxVqGw+sbfZLghDmaI5MGHW+4+GIt//ld3hx7h8AEoWpfoyspYG0G8E6p4yaOH/qCs52GlNAsOye4nAjxzlbIqFRTBiGnXwO7OszoQgaY3lCllTH5K4jAO2WmPWauR1+17+RtbNTz+Ojz4THC4n+YsbHaAomIbbdLqkk1yvPb35RO3ayjK8IaX0AavefBQWp4YTiwqq13C1YYWum1aDyNIBt2mpbEIZ299ulYHpFi4+qXbQ39ozSGD2jOe5Coxkn/nzOnQPD2e0XPjFclY/pGTn4KfaBYohxj6MMzbp64gzroTO8D0kcwzEJza8CNCOL19qCQxaL1wPGNYm0YvAP6RUGAhSoVKS1V+S+dCYd2rE8+lX6WicbPn/+lb/sctGR9BeLhBoyDXXLRG/cVKxHbC01ajqYRa8U6VYureD7omgs+6KKgM+ai1eIUmf4qHOm3h+gX+VkpeqGXdQB6jEDiC+W4BQg1Tb73SIyzizkz/d53ewAtF78x4Nw9TCvBZQ6sX47Wm4ebOZAn43rY5zWjgOMfQIyCGVTjXy+F/Z9qPHryXP2+u6kFEYZ7yR9vVHbdBZZ9T90eQAUJ78WoUpI+Cxgv7goJNv2QbjzRT7llVLwg88WXd1JbnTTJkg18R4oyMemUHes08hz906EgNEqezmnxgzDINjHKtrxG+bP8JHKDdbSweIdFu70mV0h63JF3HnezVCBie4GsYV0164TJNb1+yy3R4tbYQ==
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: lapi-hotel-system

