apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: dragoneena12/lapi-hotel-system:latest
          ports:
            - containerPort: 4000
          volumeMounts:
              - name: config
                mountPath: /app
                readOnly: true
      volumes:
        - name: config
          secret:
            secretName: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
