apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  namespace: pritunl
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: pritunl-pvc
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: pritunl-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
        selector:
          matchLabels:
            name: pritunl-pv
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: pritunl
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
