apiVersion: apps/v1
kind: Deployment
metadata:
  name: holdem-server
  namespace: holdem
  labels:
    app: holdem-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: holdem-server
  template:
    metadata:
      labels:
        app: holdem-server
    spec:
      containers:
        - name: holdem-server
          image: dragoneena12/holdem-server:latest
          ports:
            - containerPort: 8765
---
apiVersion: v1
kind: Service
metadata:
  name: holdem-server
  namespace: holdem
spec:
  selector:
    app: holdem-server
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
