kind: PersistentVolume
apiVersion: v1
metadata:
  name: docker-mailserver-pv
  labels:
    name: docker-mailserver-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: docker-mailserver
    name: docker-mailserver
  local:
    path: /mnt/sda/data/docker-mailserver
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1
