kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-pv
  labels:
    name: grafana-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: grafana
    name: grafana-pvc-grafana-0
  local:
    path: /mnt/sda/data/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1
