kind: PersistentVolume
apiVersion: v1
metadata:
  name: lapi-hotel-system-pv
  labels:
    name: lapi-hotel-system-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: lapi-hotel-system
    name: mariadb
  local:
    path: /mnt/sda/data/lapi-hotel-system
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1
