kind: PersistentVolume
apiVersion: v1
metadata:
  name: minecraft-pv
  labels:
    name: minecraft-pv
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: minecraft
    name: minecraft-pvc-minecraft-0
  local:
    path: /mnt/sda/data/minecraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node2
