kind: PersistentVolume
apiVersion: v1
metadata:
  name: openvpn-pv
  labels:
    name: openvpn-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: openvpn
    name: openvpn-pvc-openvpn-statefulset-0
  local:
    path: /mnt/sda/data/openvpn
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1
