kind: PersistentVolume
apiVersion: v1
metadata:
  name: owncloud-pv
  labels:
    name: owncloud-pv
spec:
  storageClassName: manual
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: owncloud
    name: owncloud-pvc-owncloud-0
  local:
    path: /mnt/sda/data/owncloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1
