kind: PersistentVolume
apiVersion: v1
metadata:
  name: pritunl-pv
  labels:
    name: pritunl-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/sda/data/pritunl
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1
