kind: PersistentVolume
apiVersion: v1
metadata:
  name: wireguard-pv
  labels:
    name: wireguard-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: wireguard
    name: wireguard-pvc-wireguard-statefulset-0
  local:
    path: /mnt/sda/data/wireguard
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1
