---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  url: https://argocd.lapi.gq
  application.instanceLabelKey: argocd.argoproj.io/instance
  oidc.config: |
    name: Auth0
    issuer: https://lapi.us.auth0.com/
    clientID: ijo0ZHt8E4Xv17jAlBG5UKsUaA9TZQxF
    clientSecret: I-IRp-hNsebMTHUTqGSc16qVA1Urva6QbUbmNBLAmWBovcNIcll6Q1Sl-NVk7nmR
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes:
      - openid
      - profile
      - email
      - 'https://lapi.gq/claims/groups'
