apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: dragoneena12/cdg-front:latest
          ports:
            - containerPort: 3000
          volumeMounts:
              - name: front-env
                mountPath: /.env.local
                subPath: .env.local
                readOnly: true
      volumes:
        - name: front-env
          configMap:
            name: front-env
---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
