apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: dragoneena12/cdg-front:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: front-env
              mountPath: /usr/src/app/.env.local
              subPath: .env.local
              readOnly: true
          env:
          - name: NEXT_PUBLIC_ORIGIN
            valueFrom:
              configMapKeyRef:
                name: next-env
                key: NEXT_PUBLIC_ORIGIN
          - name: NEXT_PUBLIC_API_URL
            valueFrom:
              configMapKeyRef:
                name: next-env
                key: NEXT_PUBLIC_API_URL
          - name: NEXT_PUBLIC_ASSETS_URL
            valueFrom:
              configMapKeyRef:
                name: next-env
                key: NEXT_PUBLIC_ASSETS_URL
          - name: NEXT_PUBLIC_AUTH_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: next-env
                key: NEXT_PUBLIC_AUTH_CLIENT_ID
          - name: NEXT_PUBLIC_AUTH0_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: next-env
                key: NEXT_PUBLIC_AUTH0_DOMAIN
      volumes:
        - name: front-env
          configMap:
            name: front-env
---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
