apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openvpn-statefulset
  namespace: openvpn
  labels:
    app: openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvpn
  serviceName: openvpn
  template:
    metadata:
      labels:
        app: openvpn
    spec:
      containers:
        - name: openvpn
          image: project31/aarch64-docker-openvpn:2.4.9
          ports:
            - protocol: UDP
              containerPort: 1194
          volumeMounts:
            - name: openvpn-pvc
              mountPath: /etc/openvpn
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      initContainers:
        - name: init-genconfig
          image: project31/aarch64-docker-openvpn:2.4.9
          command: ["ovpn_genconfig -u udp://vpn.lapi.gq"]
          volumeMounts:
            - name: openvpn-pvc
              mountPath: /etc/openvpn
        - name: init-genconfig
          image: project31/aarch64-docker-openvpn:2.4.9
          command: ["ovpn_initpki"]
          volumeMounts:
            - name: openvpn-pvc
              mountPath: /etc/openvpn
  volumeClaimTemplates:
    - metadata:
        name: openvpn-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: openvpn-service
  namespace: openvpn
spec:
  selector:
    app: openvpn
  ports:
    - protocol: UDP
      port: 1194
  type: LoadBalancer
