apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  selector:
    app: minecraft
  ports:
    - name: minecraft
      port: 25565
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
spec:
  replicas: 0
  selector:
    matchLabels:
      app: minecraft
  serviceName: minecraft
  template:
    metadata:
      name: minecraft
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:1.12.0-multiarch
          env:
            - name: EULA
              value: "TRUE"
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: minecraft-pvc
              mountPath: /data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node2
  volumeClaimTemplates:
    - metadata:
        name: minecraft-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 8Gi
