kube-state-metrics:
  image:
    repository: carlosedp/kube-state-metrics
    tag: v1.9.6
alertmanager:
  persistentVolume:
    storageClass: rook-ceph-block
server:
  persistentVolume:
    storageClass: rook-ceph-block
