kube-state-metrics:
  image:
    repository: k8s.gcr.io/kube-state-metrics/kube-state-metrics-arm64
    tag: 2.0.0-alpha
alertmanager:
  persistentVolume:
    storageClass: rook-ceph-block
server:
  persistentVolume:
    storageClass: rook-ceph-block
